/**
 * Model definitions for Routes and Route Completions
 * These interfaces define the structure of standard running routes and user completions
 */

/**
 * Represents a standard running route in the system
 * Routes are stored with SVG path data for visualization on the community map
 */
export interface Route {
  /** Unique identifier for the route */
  id: string;

  /** Display name of the route (e.g., "10km Vollrunde Main") */
  name: string;

  /** Total distance of the route in kilometers */
  distance: number;

  /** SVG Path definition for rendering the route on a map */
  pathData: string;

  /** Optional detailed description of the route */
  description?: string;

  /** Route difficulty level */
  difficulty?: 'EASY' | 'MODERATE' | 'HARD' | 'EXPERT';

  /** Route category/type */
  category?: 'RIVERSIDE' | 'PARK' | 'CITY' | 'TRAIL' | 'MIXED';

  /** Route emoji icon for visual representation */
  icon?: string;

  /** Indicates if the route is currently active */
  isActive?: boolean;

  /** Creation timestamp */
  createdAt?: Date;

  /** Last update timestamp */
  updatedAt?: Date;
}

/**
 * Represents a user's completion of a route
 * This is generated by the route matching algorithm when a user uploads a run
 */
export interface RouteCompletion {
  /** Unique identifier for this completion */
  id?: string;

  /** ID of the user who completed the route */
  userId: string;

  /** ID of the route that was completed */
  routeId: string;

  /** Timestamp when the route was completed */
  completedAt: Date;

  /** Percentage of the route that was completed (0-100) */
  percentage: number;

  /** Direction in which the route was run */
  direction: 'forward' | 'reverse';

  /** Accuracy of the match between the uploaded run and the standard route (0-100) */
  matchAccuracy: number;

  /** Optional reference to the run that completed this route */
  runId?: number;
}

/**
 * Extended Route interface with calculated marker position for SVG rendering
 */
export interface RouteWithPosition extends Route {
  /** Calculated position for the route marker on the SVG canvas */
  markerPosition: PathPoint;
}

/**
 * Represents a point on an SVG path with coordinates and angle
 */
export interface PathPoint {
  /** X coordinate on the SVG canvas */
  x: number;

  /** Y coordinate on the SVG canvas */
  y: number;

  /** Angle/direction at this point (in degrees) */
  angle: number;
}

/**
 * Combined interface for displaying completion data with user information
 * Used for tooltips and avatar displays
 */
export interface CompletionWithUser {
  /** The route completion data */
  completion: RouteCompletion;

  /** The user who completed the route */
  user: CompletionUser;
}

/**
 * Simplified user interface for displaying in the community map
 */
export interface CompletionUser {
  /** User ID */
  id: string;

  /** User's display name */
  name: string;

  /** URL to user's avatar image */
  avatarUrl: string;

  /** Optional first name */
  firstName?: string;

  /** Optional last name */
  lastName?: string;
}

/**
 * Statistics for a specific route
 */
export interface RouteStatistics {
  /** Route ID */
  routeId: string;

  /** Total number of completions (all percentages) */
  totalCompletions: number;

  /** Average completion percentage across all completions */
  averageCompletion: number;

  /** Number of forward direction completions */
  forwardCount: number;

  /** Number of reverse direction completions */
  reverseCount: number;

  /** Number of 100% completions */
  fullCompletions: number;

  /** Most common direction */
  primaryDirection: 'forward' | 'reverse' | 'mixed';

  /** Unique users who completed this route */
  uniqueUsers: number;
}

/**
 * Arrow definition for displaying direction indicators on routes
 */
export interface ArrowDefinition {
  /** Polyline points for the arrow */
  points: string;

  /** Marker reference ID (arrowForward or arrowReverse) */
  markerId: string;

  /** Stroke color for the arrow */
  color: string;

  /** Position percentage on the path (0-1) */
  position: number;
}

/**
 * Combined data structure for the community map
 */
export interface CommunityData {
  /** All available routes */
  routes: Route[];

  /** Map of route completions by route ID */
  completions: Map<string, RouteCompletion[]>;

  /** Map of users by user ID */
  users: Map<string, CompletionUser>;

  /** Route statistics by route ID */
  statistics: Map<string, RouteStatistics>;
}
